name: Run Tests and Store Allure Results

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          install-chromedriver: true

      - name: Verify Chromium Installation
        run: which chromium-browser

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with pytest and Allure
        env:
          DISPLAY: ":99"
        run: |
          mkdir -p allure-results
          pytest

      - name: Upload Allure results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results
